# Generated by Django 4.2 on 2023-04-11 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_desccription_listing_sold_listing_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('R', 'Records'), ('C', 'Clothing'), ('P', 'Posters'), ('M', 'Misc')], default=2022, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(null=1, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
